//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="NotificationSoap12", Namespace="http://dk.itst")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
public interface INotificationSoap12 {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dk.itst/Notify", RequestNamespace="http://dk.itst", ResponseNamespace="http://dk.itst", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    void Notify(CommonEventStructureType notification);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dk.itst/Ping", RequestNamespace="http://dk.itst", ResponseNamespace="http://dk.itst", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    void Ping();
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dk.itst")]
public partial class CommonEventStructureType {
    
    private EventInfoStructureType eventInfoStructureField;
    
    private string eventTopicField;
    
    private string eventSubscriptionReferenceField;
    
    private ExtensionStructureType extensionStructureField;
    
    private EventDetailStructureType eventDetailStructureField;
    
    /// <remarks/>
    public EventInfoStructureType EventInfoStructure {
        get {
            return this.eventInfoStructureField;
        }
        set {
            this.eventInfoStructureField = value;
        }
    }
    
    /// <remarks/>
    public string EventTopic {
        get {
            return this.eventTopicField;
        }
        set {
            this.eventTopicField = value;
        }
    }
    
    /// <remarks/>
    public string EventSubscriptionReference {
        get {
            return this.eventSubscriptionReferenceField;
        }
        set {
            this.eventSubscriptionReferenceField = value;
        }
    }
    
    /// <remarks/>
    public ExtensionStructureType ExtensionStructure {
        get {
            return this.extensionStructureField;
        }
        set {
            this.extensionStructureField = value;
        }
    }
    
    /// <remarks/>
    public EventDetailStructureType EventDetailStructure {
        get {
            return this.eventDetailStructureField;
        }
        set {
            this.eventDetailStructureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dk.itst")]
public partial class EventInfoStructureType {
    
    private string eventIdentifierField;
    
    private string eventProducerReferenceField;
    
    private System.DateTime eventRegistrationDateTimeField;
    
    private EventObjectStructureType eventObjectStructureField;
    
    private ExtensionStructureType extensionStructureField;
    
    private System.Nullable<bool> isLastNotificationField;
    
    private bool isLastNotificationFieldSpecified;
    
    /// <remarks/>
    public string EventIdentifier {
        get {
            return this.eventIdentifierField;
        }
        set {
            this.eventIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string EventProducerReference {
        get {
            return this.eventProducerReferenceField;
        }
        set {
            this.eventProducerReferenceField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EventRegistrationDateTime {
        get {
            return this.eventRegistrationDateTimeField;
        }
        set {
            this.eventRegistrationDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public EventObjectStructureType EventObjectStructure {
        get {
            return this.eventObjectStructureField;
        }
        set {
            this.eventObjectStructureField = value;
        }
    }
    
    /// <remarks/>
    public ExtensionStructureType ExtensionStructure {
        get {
            return this.extensionStructureField;
        }
        set {
            this.extensionStructureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsLastNotification {
        get {
            return this.isLastNotificationField;
        }
        set {
            this.isLastNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsLastNotificationSpecified {
        get {
            return this.isLastNotificationFieldSpecified;
        }
        set {
            this.isLastNotificationFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dk.itst")]
public partial class EventObjectStructureType {
    
    private string objectTypeReferenceField;
    
    private string eventObjectReferenceField;
    
    private string actionSchemeReferenceField;
    
    private string eventObjectActionCodeField;
    
    /// <remarks/>
    public string ObjectTypeReference {
        get {
            return this.objectTypeReferenceField;
        }
        set {
            this.objectTypeReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string EventObjectReference {
        get {
            return this.eventObjectReferenceField;
        }
        set {
            this.eventObjectReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string actionSchemeReference {
        get {
            return this.actionSchemeReferenceField;
        }
        set {
            this.actionSchemeReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string EventObjectActionCode {
        get {
            return this.eventObjectActionCodeField;
        }
        set {
            this.eventObjectActionCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dk.itst")]
public abstract partial class EventDetailStructureType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dk.itst")]
public partial class ExtensionStructureType {
    
    private System.Guid idField;
    
    private object[] itemField;
    
    /// <remarks/>
    public System.Guid ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public object[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}
